


export const ActionType = {
  VIEW: 'VIEW',
  CREATE: 'CREATE',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
  FULL_VIEW: 'FULL_VIEW',
  EXPORT_DATA: 'EXPORT_DATA',
  HOLD_BATCH: 'HOLD_BATCH',
  ASSIGN_PERMISSION: 'ASSIGN_PERMISSION',
} as const;

export type ActionType = (typeof ActionType)[keyof typeof ActionType];



export const Common = {
  Actions: {
    CAN_ADD: 'CREATE',
    CAN_UPDATE: 'UPDATE',
    CAN_DELETE: 'DELETE',
    CAN_VIEW: 'VIEW',
    CAN_ASSIGN_PERMISSION: 'ASSIGN_PERMISSION',
  },
  Modules: {
    DASHBOARD: {
      DASHBOARD: 'DASHBOARD',
    },
    USER_CONFIGURATION: {
      USER_CONFIGURATION: 'USER_CONFIGURATION',
      USERS: 'USERS_USERS',
      ROLES: 'USERS_ROLES',
      CONFIGURATION_LIST: 'CONFIGURATION_LIST',
    },
    MASTER: {
      MASTER: 'MASTER',
      // Sub-group codes (used for the sidebar tree, no CRUD page actions).
      PURCHASING: 'MASTER_PURCHASING',
      ORGANIZATION: 'MASTER_ORGANIZATION',
      FINANCE_TAX: 'MASTER_FINANCE_TAX',
      GEOGRAPHY: 'MASTER_GEOGRAPHY',
      // Purchasing leaves
      VENDOR: 'MASTER_VENDOR',
      VENDOR_SITE: 'MASTER_VENDOR_SITE',
      VENDOR_CATEGORY: 'MASTER_VENDOR_CATEGORY',
      APPLICANT_TYPE: 'MASTER_APPLICANT_TYPE',
      ITEM: 'MASTER_ITEM',
      ITEM_TYPE: 'MASTER_ITEM_TYPE',
      ITEM_CATEGORY: 'MASTER_ITEM_CATEGORY',
      UOM: 'MASTER_UOM',
      PAYMENT_TERMS: 'MASTER_PAYMENT_TERMS',
      // Organization leaves
      DEPARTMENT: 'MASTER_DEPARTMENT',
      SUBDEPARTMENT: 'MASTER_SUBDEPARTMENT',
      COST_CENTER: 'MASTER_COST_CENTER',
      ENTITY: 'MASTER_ENTITY',
      CENTER: 'MASTER_CENTER',
      // Finance & Tax leaves
      COA: 'MASTER_COA',
      TDS: 'MASTER_TDS',
      GST: 'MASTER_GST',
      VOUCHER: 'MASTER_VOUCHER',
      // Geography leaves
      COUNTRY: 'MASTER_COUNTRY',
      ZONE: 'MASTER_ZONE',
      STATE: 'MASTER_STATE',
      CITY: 'MASTER_CITY',
    },
    WORKFLOW: {
      WORKFLOW: 'WORKFLOW',
      WORKFLOW_V1: 'WORKFLOW_V1',
      WORKFLOW_V2: 'WORKFLOW_V2',
    },
    APPROVALS: {
      APPROVALS: 'APPROVALS',
      ITEM_APPROVAL: 'APPROVAL_ITEM',
      VENDOR_APPROVAL: 'APPROVAL_VENDOR',
      BUDGET_APPROVAL: 'APPROVAL_BUDGET',
    },
    PROCUREMENT: {
      PROCUREMENT: 'PROCUREMENT',
      PURCHASE_REQUEST: 'PROCUREMENT_PURCHASE_REQUEST',
      RATE_CONTRACT: 'PROCUREMENT_RATE_CONTRACT',
      PURCHASE_ORDER: 'PROCUREMENT_PURCHASE_ORDER',
      DIRECT_INVOICE: 'PROCUREMENT_DIRECT_INVOICE',
    },
    FINANCE: {
      FINANCE: 'FINANCE',
      BUDGETS: 'FINANCE_BUDGETS',
    },
  },
} as const;



export const RoleType = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  MANAGER: 'MANAGER',
  PURCHASER: 'PURCHASER',
  FINANCE: 'FINANCE',
  FACULTY_HEAD: 'FACULTY_HEAD',
  FACULTY: 'FACULTY',
  OPERATION_MANAGER: 'OPERATION_MANAGER',
  SALES_MANAGER: 'SALES_MANAGER',
  ACCOUNT_MANAGER: 'ACCOUNT_MANAGER',
} as const;

export type RoleType = (typeof RoleType)[keyof typeof RoleType];
